# Generated by Django 3.2.5 on 2022-01-25 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=11)),
                ('user_addr', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.DateField()),
                ('size', models.CharField(max_length=1)),
                ('neutered', models.CharField(max_length=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mypageapp.user')),
            ],
        ),
    ]
