# Generated by Django 3.2.5 on 2022-01-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_profile_photo',
            new_name='pet_img',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo',
            new_name='profile_img',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='user_phone',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='mf',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='nt',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_addr',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(max_length=50),
        ),
    ]
