# Generated by Django 3.2.5 on 2022-01-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0002_auto_20220124_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='neutered',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
