# Generated by Django 3.2.5 on 2022-01-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0004_auto_20220124_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mypageapp.user'),
        ),
    ]
