# Generated by Django 3.2.5 on 2022-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0006_auto_20220124_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
