# Generated by Django 3.2.5 on 2022-01-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0007_alter_pet_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
    ]
