# Generated by Django 3.2.5 on 2022-01-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypageapp', '0008_remove_user_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_img',
        ),
    ]
